#!/usr/bin/env python3

class Configuration(object):
    modifiers = list()
    file_format = None
    verbose = False
    input_filename = None
    output_filename = None

    def __init__(self, cmdline_argv):
        argv = cmdline_argv[1:]

        #args without dash are self.modifiers
        for arg in argv:
            if arg[0] == '-':
                self.modifiers.append(arg)
                argv.remove(arg)

        if not argv:
            raise Exception('Too few arguments.')

        self.input_filename = argv[0]
        self.output_filename = argv[1] if argv[1:] else None

        self.verbose = '-v' in self.modifiers

        extension = self.input_filename.split('.')[-1].lower()
        if extension in ('xml', 'csv'):
            self.file_format = extension
        elif '-xml' in self.modifiers:
            self.file_format = 'xml'
        elif '-csv' in self.modifiers:
            self.file_format = 'csv'
        else:
            raise Exception('Unknown file format.')


if __name__ == '__main__':
    import logging
    import sys
    import pyipko

    logging.basicConfig(level=logging.DEBUG)
    config = Configuration(sys.argv)
    converter = pyipko.Converter()

    if config.file_format == 'xml':
        converter.parse_from_XML(config.input_filename)
    elif config.file_format == 'csv':
        converter.parse_from_CSV(config.input_filename, 'iso-8859-2')

    mt940 = converter.to_mt940()

    if config.verbose:
        print(mt940)

    if config.output_filename:
        with open(config.output_filename, 'w', encoding='cp852', errors='ignore') as fp:
            fp.write(mt940)
