#!/usr/bin/env python3
import logging
import argparse
import sys
import pyipko

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)

    logger = logging.getLogger(__name__)

    parser = argparse.ArgumentParser(
            description='Convert xml or csv file into mt940 format.')
    parser.add_argument('-v', dest='verbose', action='store_true',
            help='be verbose, print everything')
    parser.add_argument(dest='input_filename', action='store',
            help='input file to be parsed')
    parser.add_argument('-o', dest='output_file' ,action='store',
            default=None, required=False,
            help='output file, if not specified the output will go to stdout')
    parser.add_argument('-f', dest='file_format' ,action='store',
            default=None, required=False,
            choices=('xml', 'csv'),
            help='input file format')

    #config = Configuration(sys.argv)
    config = parser.parse_args()
    logger.debug('Namespace = %s', config)

    if not config.verbose:
        logging.basicConfig(level=logging.INFO)

    converter = pyipko.Converter()

    if config.file_format == 'xml':
        converter.parse_from_XML(config.input_filename)
    elif config.file_format == 'csv':
        converter.parse_from_CSV(config.input_filename, 'iso-8859-2')

    mt940 = converter.to_mt940()

    if config.verbose:
        print(mt940)

    if config.output_filename:
        with open(config.output_filename, 'w', encoding='cp852', errors='ignore') as fp:
            fp.write(mt940)
